title: "FinTechXHub"
description: "ผสมผสานระหว่างการเงิน (Finance) และเทคโนโลยี (Technology)"
baseurl: "" # ใช้ในกรณีที่ repository ของคุณไม่ได้ชื่อเป็น root (โปรเจกต์ย่อย)
url: "kris-p19.github.io" # URL ของ GitHub Pages fintechxhub.com
theme: jekyll-theme-slate # เลือกธีม Jekyll ที่ต้องการ
facebook: "https://www.facebook.com/profile.php?id=61575500563169"